import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  Ban,
  BarChart2,
  BookOpen,
  CalendarDays,
  ClipboardList,
  Cloud,
  DollarSign,
  Factory,
  FileText,
  Files,
  Gauge,
  HandCoins,
  History,
  Home,
  Inbox,
  Landmark,
  LayoutDashboard,
  Layers,
  Mail,
  Map as MapIcon,
  Navigation,
  Package,
  Plus,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Snowflake,
  Tag,
  Timer,
  PackageX,
  TrendingUp,
  Truck,
  Tv,
  UserCheck,
  UserCircle,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Wrench,
} from 'lucide-react'

/**
 * Íconos de las pantallas del catálogo, por nombre (2026-09-22). El catálogo
 * (`catalogo.ts`) guarda solo el NOMBRE: lo importa App.tsx para los roles de
 * cada ruta y entraba en el chunk del login con los 40 íconos de todos los
 * menús. Los menús (sidebar, navbar, panel, buscador) resuelven acá con
 * `iconoDe`, y viven en chunks que se cargan después de entrar.
 */
export const ICONOS = {
  Activity: Activity,
  AlertTriangle: AlertTriangle,
  Ban: Ban,
  BookOpen: BookOpen,
  BarChart2: BarChart2,
  CalendarDays: CalendarDays,
  ClipboardList: ClipboardList,
  Cloud: Cloud,
  DollarSign: DollarSign,
  Factory: Factory,
  FileText: FileText,
  Files: Files,
  Gauge: Gauge,
  HandCoins: HandCoins,
  History: History,
  Home: Home,
  Inbox: Inbox,
  Landmark: Landmark,
  LayoutDashboard: LayoutDashboard,
  Layers: Layers,
  Mail: Mail,
  Map: MapIcon,
  Navigation: Navigation,
  Package: Package,
  Plus: Plus,
  Scale: Scale,
  Search: Search,
  Settings: Settings,
  ShieldCheck: ShieldCheck,
  ShoppingCart: ShoppingCart,
  Snowflake: Snowflake,
  Tag: Tag,
  Timer: Timer,
  PackageX: PackageX,
  TrendingUp: TrendingUp,
  Truck: Truck,
  Tv: Tv,
  UserCheck: UserCheck,
  UserCircle: UserCircle,
  UserCog: UserCog,
  Users: Users,
  Wallet: Wallet,
  Warehouse: Warehouse,
  Wrench: Wrench,
} as const satisfies Record<string, LucideIcon>

export type NombreIcono = keyof typeof ICONOS

export const iconoDe = (nombre: NombreIcono): LucideIcon => ICONOS[nombre]
